# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Laiane Muckler
email: laianecm@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  web developer in construction...
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://laimuckler.github.io" # the base hostname & protocol for your site
twitter_username: lcmcklr
github_username:  laimuckler

# Build settings
markdown: kramdown
